### ISSUE TITLE
Pre-commit: Add examples on how to exclude multiple files / directories

### ISSUE THREAD

**Issue by vid553** [IRNAS/irnas-zephyr-template#25]
## Context

It is often needed that multiple files are excluded from pre-commit checks. It may be that we want to skip all checks or only a specific hook for a specific file.

According to the docs, the exclude property accepts a regular expression, but I didn't manage to get it to work properly, it only worked for a single entry. It would be helpful to have some examples in the documentation.

Relevant links:
- https://pre-commit.com/#regular-expressions
- https://stackoverflow.com/questions/75178854/how-do-i-exclude-multiple-folders-and-or-file-patterns-from-pre-commit-analysis

## Required steps / Implementation details

Provide examples in the docs that show how to exclude multiple files / directories globally and how to exclude them from a specific tool (hook).

## Definition of Done

Described feature is documented.

**Comment by vid553** [comment]
Confirming that both examples work.
Thank you.

**Comment by MarkoSagadin** [comment]
@vid553 for added visibility: https://github.com/IRNAS/irnas-guidelines-docs/commit/df30141eafbfc959c1f21104ab2a4f410cfe9917
